create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "Anyone can submit messages" on public.messages;
drop policy if exists "Authenticated users can read messages" on public.messages;
drop policy if exists "Authenticated users can update messages" on public.messages;
drop policy if exists "Authenticated users can delete messages" on public.messages;

create policy "Anyone can submit messages"
on public.messages for insert
to anon, authenticated
with check (true);

create policy "Authenticated users can read messages"
on public.messages for select
to authenticated
using (true);

create policy "Authenticated users can update messages"
on public.messages for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete messages"
on public.messages for delete
to authenticated
using (true);
