-- Run this once in Supabase Dashboard > SQL Editor
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  subject text,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

-- Anyone can submit the public contact form.
create policy "Anyone can submit messages"
on public.messages for insert
to anon, authenticated
with check (true);

-- Only authenticated admin users can read messages.
create policy "Authenticated users can read messages"
on public.messages for select
to authenticated
using (true);

-- Optional: add your admin account in Authentication > Users > Add user
-- Email: rahatbddb@gmail.com
-- Set a password there; do not put it in this file.
